name: Python Testes Automtizados

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Intação do Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Rodar testes
      run: PYTHONPATH=src/ python -m unittest
