name: Python Testes Automtizados

on:
  push:
    branches: [pipeline]
  pull_request: 
    branches: [pipeline]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Intação do Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Rodar testes da calculadora
      run: python -m unittest PYTHONPATH engSof2Exerc01/testUnitPython/calculadora/calculadora_test.py

    - name: Rodar teste de verificação se é par
      run: python -m unittest 'engSof2Exerc01/testUnitPython/Verificar_par_test.py'